In [1]:
print("class17")

class17


In [ ]:
import numpy as np 
import pandas as pd 

/var/folders/lf/67sx335n7gd5qzz5dq8sj93w0000gn/T/ipykernel_32475/1662815981.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [9]:
# numpy - numerical python
df= pd.read_csv("test.csv")
df

x   y
0    1   2
1    5   4
2   45  90
3   32   1
4   56  90
5  456   3

In [ ]:
df['x']

0      1
1      5
2     45
3     32
4     56
5    456
Name: x, dtype: int64

In [14]:
type(df['y'])

pandas.core.series.Series

In [15]:
df['x']

0      1
1      5
2     45
3     32
4     56
5    456
Name: x, dtype: int64

In [16]:
df['y']

0     2
1     4
2    90
3     1
4    90
5     3
Name: y, dtype: int64

In [ ]:
# complex class, read from csv - do the operation
class complexNumber:
    def __init__(self,real,img):
        self.real= real
        self.img= img
    def __rep__(self):
        if self.img<0:
            print(self.real, "-",abs(self.img),"j" )
        else:
            print(self.real, "+",abs(self.img),"j" )
    def __add__(self, other):
        a= self.real+other.real
        b= self.img+other.img
        return complexNumber(a,b)
    def __sub__(self, other):
        a= self.real+other.real
        b= self.img-other.img
        return complexNumber(a,b)    
    def __mul__(self,other):
        a= self.real*other.real-self.img*other.img
        b=self.real*other.img+self.img*other.real
        return complexNumber(a,b)
    
for x in df['x']:
    for y in df['y']:
        t= complexNumber(x,y)
        t.__rep__()
        

1 + 2 j
5 + 2 j
45 + 2 j
32 + 2 j
56 + 2 j
456 + 2 j


In [21]:
# dynamic allocation vs array
a = np.array(42)
a

array(42)

In [27]:
b= np.array([1,2,3,4,5])
b
c= np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [23]:
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.data)

0 () 1 int64 8 <memory at 0x12aace200>


In [ ]:
print(b.ndim, b.shape, b.size, b.dtype, b.itemsize, b.data) 

1 (5,) 5 int64 8 <memory at 0x13a0877c0>


In [28]:
e= np.arange(15).reshape(3,5)
print(c,e)


[[1 2 3 4 5]
 [6 7 8 9 0]] [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [33]:
print(e.ndim, e.shape, e.size, e.dtype, e.itemsize, e.data)

2 (3, 5) 15 int64 8 <memory at 0x12a959700>


In [30]:
print(len(b))

5


In [32]:
for i in range(len(b)):
    print(b[i])

1
2
3
4
5


In [ ]:
ran = np.arange(1,5,0.5) # 1 to 5 in steps of 0.5
print(ran, type(ran))

from numpy import pi
x= np.linspace(0,2,9)  # from zero to 2 in 9 steps
print(x)
x= np.linspace(0,2*pi, 100) # from 0 to 2pi in 100 number of steps
y= np.sin(x)
print(y) 

[1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.ndarray'>
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -

In [ ]:
from math import sin, pi
for i in range(0, 2*pi,0.5): #'float' object cannot be interpreted as an integer
    print(sin(i))

TypeError: 'float' object cannot be interpreted as an integer

In [37]:
a= np.array([[1,2],[4,4]])
b= np.array([[1,2],[4,4]])
print(a*b) # element wise product called- 
print(a@b)
print(np.dot(a,b))
print(a.dot(b))

[[ 1  4]
 [16 16]]
[[ 9 10]
 [20 24]]
[[ 9 10]
 [20 24]]
[[ 9 10]
 [20 24]]


In [ ]:
# take matrix class and read data from numpy
# use zip 
